var players = [{
    "name": "Stephen Curry",
    "team": "GSW",
    "gamesPlayed":   20,
    "minutesPerGame": 34.3,
    "trueShootingPercentage": .700,
    "assistRatio": 18.4,
    "turnoverRatio": 11.1,
    "usageRate": 32.3,
    "offsensiveReboundRate": 1.7,
    "defensiveReboundRate":  13.6,
    "reboundRate": 8.1,
    "playerEfficiencyRating": 35.18,
    "valueAdded": 247.2,
    "estimatedWinAverage": 8.2
},
{
    "name": "Russell Westbrook",
    "team": "OKC",
    "gamesPlayed":   18,
    "minutesPerGame": 34.5,
    "trueShootingPercentage": .576,
    "assistRatio": 25.1,
    "turnoverRatio": 13.5,
    "usageRate": 37.0,
    "offsensiveReboundRate": 6.8,
    "defensiveReboundRate":  16.6,
    "reboundRate": 11.9,
    "playerEfficiencyRating": 31.94,
    "valueAdded": 194.1,
    "estimatedWinAverage": 6.5
},
{
    "name": "Kevin Durant",
    "team": "OKC",
    "gamesPlayed": 12,
    "minutesPerGame": 35.2,
    "trueShootingPercentage": .659,
    "assistRatio": 12.4,
    "turnoverRatio": 9.1,
    "usageRate": 28.1,
    "offsensiveReboundRate": 0.8,
    "defensiveReboundRate":  21.6,
    "reboundRate": 11.6,
    "playerEfficiencyRating": 31.57,
    "valueAdded": 132.7,
    "estimatedWinAverage": 4.4
},
{
    "name": "DeMarcus Cousins",
    "team": "SAC",
    "gamesPlayed":   11,
    "minutesPerGame": 33.4,
    "trueShootingPercentage": .562,
    "assistRatio":  9.1,
    "turnoverRatio": 10.2,
    "usageRate": 33.9,
    "offsensiveReboundRate": 7.3,
    "defensiveReboundRate":  29.0,
    "reboundRate": 18.0,
    "playerEfficiencyRating": 27.34,
    "valueAdded": 86.8,
    "estimatedWinAverage": 2.9
},
{
    "name": "Blake Griffin",
    "team": "LAC",
    "gamesPlayed": 19,
    "minutesPerGame": 34.1,
    "trueShootingPercentage": .576,
    "assistRatio": 16.9,
    "turnoverRatio": 8.1,
    "usageRate": 29.6,
    "offsensiveReboundRate": 6.0,
    "defensiveReboundRate":  20.2,
    "reboundRate": 13.1,
    "playerEfficiencyRating": 27.11,
    "valueAdded": 150.8,
    "estimatedWinAverage": 5.0
},
{
    "name": "Kawhi Leonard",
    "team": "SA",
    "gamesPlayed":   18,
    "minutesPerGame": 34.2,
    "trueShootingPercentage": .595,
    "assistRatio": 11.6,
    "turnoverRatio": 6.0,
    "usageRate": 24.5,
    "offsensiveReboundRate": 4.9,
    "defensiveReboundRate":  18.4,
    "reboundRate": 12.0,
    "playerEfficiencyRating": 26.73,
    "valueAdded": 148.9,
    "estimatedWinAverage": 5.0
},
{
    "name": "Paul George",
    "team": "IND",
    "gamesPlayed":  17,
    "minutesPerGame": 36.1,
    "trueShootingPercentage": .602,
    "assistRatio": 14.2,
    "turnoverRatio": 11.3,
    "usageRate": 30.3,
    "offsensiveReboundRate": 4.2,
    "defensiveReboundRate":  20.4,
    "reboundRate": 12.3,
    "playerEfficiencyRating": 26.65,
    "valueAdded": 148,
    "estimatedWinAverage": 4.9
},
{
    "name": "Derrick Favors",
    "team": "UTAH",
    "gamesPlayed":  15 ,
    "minutesPerGame": 31.0,
    "trueShootingPercentage": .576,
    "assistRatio": 9.1,
    "turnoverRatio": 8.7,
    "usageRate": 22.3,
    "offsensiveReboundRate": 10.1,
    "defensiveReboundRate":  22.6,
    "reboundRate": 16.2,
    "playerEfficiencyRating": 26.48,
    "valueAdded": 104.0,
    "estimatedWinAverage": 3.5
},
{
    "name": "Lebron James",
    "team": "CLE",
    "gamesPlayed":  18,
    "minutesPerGame": 36.5,
    "trueShootingPercentage": .562,
    "assistRatio": 19.8,
    "turnoverRatio": 10.6,
    "usageRate": 32.0,
    "offsensiveReboundRate": 4.7,
    "defensiveReboundRate":  18.8,
    "reboundRate": 12.0,
    "playerEfficiencyRating": 26.42,
    "valueAdded": 156.1,
    "estimatedWinAverage": 5.2
},
{
    "name": "Hassan Whiteside",
    "team": "MIA",
    "gamesPlayed":   16,
    "minutesPerGame": 29.2,
    "trueShootingPercentage": .601,
    "assistRatio": 1.8,
    "turnoverRatio": 15.2,
    "usageRate": 18.9,
    "offsensiveReboundRate": 11.7,
    "defensiveReboundRate":  29.3,
    "reboundRate": 20.8,
    "playerEfficiencyRating": 26.01,
    "valueAdded": 107.4,
    "estimatedWinAverage": 3.6
}];
